### ISSUE TITLE
I'd like to know how to use this

### ISSUE THREAD

**Issue by yarving** [Luke-Nukem/i3_configs#1]
Would you please offer a script to show how to use your configs?

**Comment by Luke-Nukem** [comment]
Just make sure you have the suggested programs installed, and copy the files in https://github.com/Luke-Nukem/i3_configs/i3_configs to ~/.i3/

You'll likely need "exec i3" in ~/.xinitrc as well if you aren't using a gui login screen.

**Comment by yarving** [comment]
Thanks.
